# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'mattiascibien/aldo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile.amd64'
        tags: '$(tag)'
    # - task: Docker@2
    #   inputs:
    #     containerRegistry: 'DockerHub'
    #     command: 'login'
    - bash: docker buildx build --no-cache --push --platform linux/arm64 --tag mattiascibien/aldo:$(tag)  $(Build.SourcesDirectory)/Aldo/ 
    # - task: Docker@2
    #   displayName: Build an image
    #   inputs:
    #     containerRegistry: 'DockerHub'
    #     repository: 'mattiascibien/aldo'
    #     command: 'buildAndPush'
    #     Dockerfile: '**/Dockerfile.arm64'
    #     tags: '$(tag)'
    
