# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build Docker Image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: 'Login To DockerHub'
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'
    - bash: docker buildx create --bootstrap --driver docker-container --use --platform linux/amd64,linux/arm64
      displayName: 'Create multi-arch Docker Builder'
    - bash: cd $(Build.SourcesDirectory)/Aldo/ && docker buildx build --no-cache --push --platform linux/amd64,linux/arm64 -f Dockerfile.amd64 --tag mattiascibien/aldo:$(tag) .
      displayName: 'Build and push Image'